In [18]:
import pandas as pd 
import numpy as np 
import requests

1. Download & Get "Building Detail" data

In [19]:
def download_BuildingDetails():

    # Direct URL to the CSV file
    csv_url = "https://services2.arcgis.com/11XBiaBYA9Ep0yNJ/arcgis/rest/services/BuildingDetails/FeatureServer/replicafilescache/BuildingDetails_-7832066962313449791.csv"

    # Send a GET request to the URL
    response = requests.get(csv_url)

    # Check if the request was successful
    if response.status_code == 200:
        # Write the content to a CSV file
        with open("Building_Details.csv", "wb") as file:
            file.write(response.content)
        print("CSV file downloaded successfully!")
    else:
        print("Failed to download CSV file.")

    file_path = r"Building_Details.csv"

    building_detail = pd.read_csv(file_path)

    return building_detail

building_detail = download_BuildingDetails()
building_detail

CSV file downloaded successfully!

C:\Users\kkoja\AppData\Local\Temp\ipykernel_17972\1560510466.py:20: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  building_detail = pd.read_csv(file_path)

,BUILDING_ID,BUILDING_NAME,NAME_STATUS,NAME_APPROVED_DATE,BUILDING_OWNER,YEAR_OF_CONSTRUCTION,INSTALL_YEAR_CONFIDENCE,TOTAL_SQUARE_FOOTAGE,TOTAL_SQFT_CONFIDENCE,HRM_INTEREST,...,SOURCE,SOURCE_ACCURACY,CIVIC_ID,PID,CIVIC_NUMBER,STREET_NAME,STREET_TYPE,COMMUNITY_NAME,DISTRICT,ObjectId
0,BL1,NaN,NaN,NaN,PRIV,NaN,NaN,NaN,NaN,NaN,...,CBM PROJ,IN,1578,457481,133,MICMAC,DR,HAMMONDS PLAINS,14.0,1
1,BL10,NaN,NaN,NaN,PRIV,NaN,NaN,NaN,NaN,NaN,...,CBM PROJ,IN,15906,322065,89,GORDON,AVE,HALIFAX,10.0,2
2,BL100,EAST PRESTON RECREATION CENTRE,A,NaN,HRM,1996.0,2.0,16384.0,2.0,Y,...,FIRE INSP,IN,104912,40188807,24,BROOKS,DR,EAST PRESTON,4.0,3
3,BL100,EAST PRESTON RECREATION CENTRE,A,NaN,HRM,1996.0,2.0,16384.0,2.0,Y,...,AMP,IN,104912,40188807,24,BROOKS,DR,EAST PRESTON,4.0,4
4,BL1000,NaN,NaN,NaN,PRIV,NaN,NaN,NaN,NaN,NaN,...,HRMDM,IN,34878,460089,91,FENERTY,RD,MIDDLE SACKVILLE,14.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148304,BL99994,NaN,NaN,NaN,PRIV,NaN,NaN,NaN,NaN,NaN,...,HRMCA,IN,106954,40532319,45,TWO RIVERS,DR,MINEVILLE,2.0,148305
148305,BL99995,NaN,NaN,NaN,PRIV,NaN,NaN,NaN,NaN,NaN,...,HRMCA,IN,106981,40579112,49,TWO RIVERS,DR,MINEVILLE,2.0,148306
148306,BL99996,NaN,NaN,NaN,PRIV,NaN,NaN,NaN,NaN,NaN,...,HRMCA,IN,107186,40579120,1,RIVERFRONT,CRT,MINEVILLE,2.0,148307
148307,BL99998,NaN,NaN,NaN,PRIV,NaN,NaN,NaN,NaN,NaN,...,HRMCA,IN,107185,40579138,5,RIVERFRONT,CRT,MINEVILLE,2.0,148308
148308,BL99999,NaN,NaN,NaN,PRIV,NaN,NaN,NaN,NaN,NaN,...,HRMCA,IN,107251,40579146,9,RIVERFRONT,CRT,MINEVILLE,2.0,148309

2. Download & Get " HRM Building Energy Consumption" Data

In [20]:
def download_BuildingEnergyConsumption():

    # Direct URL to the CSV file
    csv_url = "https://services2.arcgis.com/11XBiaBYA9Ep0yNJ/arcgis/rest/services/HRM_Building_Energy_Usage/FeatureServer/replicafilescache/HRM_Building_Energy_Usage_-3651640421373328302.csv"

    # Send a GET request to the URL
    response = requests.get(csv_url)

    # Check if the request was successful
    if response.status_code == 200:
        # Write the content to a CSV file
        with open("HRM_Building_Energy_Usage.csv", "wb") as file:
            file.write(response.content)
        print("CSV file downloaded successfully!")
    else:
        print("Failed to download CSV file.")

    file_path = r"HRM_Building_Energy_Usage.csv"

    energy_usage = pd.read_csv(file_path)

    return energy_usage

energy_usage = download_BuildingEnergyConsumption()
energy_usage

CSV file downloaded successfully!

,Energy ID,Energy Type,Portfolio Manager Property ID,Portfolio Manager Property Name,HRM Building ID,Meter ID,Start Date,End Date,Consumption,Unit of Measure,Cost,ObjectId
0,2010806509,Natural Gas,6303414,Halifax City Hall,BL243,41522813,1/1/2018 12:00:00 AM,2/1/2018 12:00:00 AM,316.16,GJ (Gigajoules),4804.96,1
1,2010806510,Natural Gas,6303414,Halifax City Hall,BL243,41522813,2/1/2018 12:00:00 AM,3/1/2018 12:00:00 AM,281.14,GJ (Gigajoules),4385.44,2
2,2273984240,Natural Gas,6303414,Halifax City Hall,BL243,41522813,3/1/2018 12:00:00 AM,4/1/2018 12:00:00 AM,270.95,GJ (Gigajoules),4156.28,3
3,2273984241,Natural Gas,6303414,Halifax City Hall,BL243,41522813,4/1/2018 12:00:00 AM,5/1/2018 12:00:00 AM,201.76,GJ (Gigajoules),2928.71,4
4,2273984242,Natural Gas,6303414,Halifax City Hall,BL243,41522813,5/1/2018 12:00:00 AM,6/1/2018 12:00:00 AM,116.56,GJ (Gigajoules),1528.73,5
...,...,...,...,...,...,...,...,...,...,...,...,...
28787,8410612543,Electricity,16377864,Hubbards Recreation Centre,BL519,108784554,4/10/2024 12:00:00 AM,4/16/2024 12:00:00 AM,189.00,kWh (kilowatt-hours),33.16,28788
28788,8410612542,Electricity,16377864,Hubbards Recreation Centre,BL519,108784554,4/16/2024 12:00:00 AM,6/11/2024 12:00:00 AM,1769.00,kWh (kilowatt-hours),313.17,28789
28789,8619278812,Electricity,16377864,Hubbards Recreation Centre,BL519,108784554,6/11/2024 12:00:00 AM,8/12/2024 12:00:00 AM,761.00,kWh (kilowatt-hours),134.72,28790
28790,8828755042,Electricity,16377864,Hubbards Recreation Centre,BL519,108784554,8/12/2024 12:00:00 AM,10/10/2024 12:00:00 AM,504.00,kWh (kilowatt-hours),89.22,28791
28791,9013455368,Electricity,16377864,Hubbards Recreation Centre,BL519,108784554,10/10/2024 12:00:00 AM,12/10/2024 12:00:00 AM,1038.00,kWh (kilowatt-hours),183.76,28792

3. Manipulate Data

,BUILDING_ID,BUILDING_NAME,YEAR_OF_CONSTRUCTION,TOTAL_SQUARE_FOOTAGE,BUILDING_CLASSIFICATION,BUILDING_USE
0,BL1,NaN,NaN,NaN,Residential,RESIDENTIAL
1,BL10,NaN,NaN,NaN,Institutional,DAYCARE
3,BL100,EAST PRESTON RECREATION CENTRE,1996.0,16384.0,Recreation/Culture and Entertainment,RECREATION FACILITY
4,BL1000,NaN,NaN,NaN,Residential,RESIDENTIAL
6,BL10000,NaN,NaN,NaN,Residential,RESIDENTIAL
...,...,...,...,...,...,...
148304,BL99994,NaN,NaN,NaN,Residential,RESIDENTIAL
148305,BL99995,NaN,NaN,NaN,Residential,RESIDENTIAL
148306,BL99996,NaN,NaN,NaN,Residential,RESIDENTIAL
148307,BL99998,NaN,NaN,NaN,Residential,RESIDENTIAL
148308,BL99999,NaN,NaN,NaN,Residential,RESIDENTIAL

In [ ]:


energy_usage.drop_duplicates()
energy_usage